services:
  spring:
    build:
      context: ../../
    restart: unless-stopped
    depends_on:
      - redis
    # network_mode: "host" 삭제

  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - ./caddy_data:/data
    # network_mode: "host" 삭제

  livekit:
    image: livekit/livekit-server:v1.9.0
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"  # livekit은 그대로 둬도 됨

  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    volumes:
      - ./redis.conf:/etc/redis.conf
    # network_mode: "host" 삭제
